id: P1E201ECD
initial_creation_type: input
source_metadata:
  title: Khandro Tsering Chödrön Series
  language: fr
  description: 'Texts related to Khandro Tsering Chödrön (mkha'' ''gro tshe ring chos
    sgron, 1929–2011), spiritual consort of Jamyang Khyentse Chökyi Lodrö:'
  volume:
    fa5a662eef834673aa6ae063e7efb8f4:
      title: 'Beautiful String of Jewels: A Heart Advice'
      parent: Advice
    71266dd5d95349129ab80d3d12f85cd3:
      title: Khandro's Plea
      parent: Advice
    e0b93e5f56c64b87934c938f25ef1ded:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö and Khandro
        Tsering Chödrön
      parent: Long Life Prayers
    9a5ccc97193b46438c8247eed7cbb7bc:
      title: Prayer for the Long Life of Khandro Tsering Chödrön
      parent: Long Life Prayers
    23b6d021103c40e5ace52f606399a52f:
      title: Prayer to Khandro Tsering Chödrön
      parent: Prayers
    1e90b21d70ac41b49f7ab71e25b53493:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T00:17:36.400946'
last_modified_at: '2022-03-01T00:17:36.400948'
